// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj29N9-VwGgJQ4PM_hoSGvVr41J0KiG2Q',
    appId: '1:526856370239:web:b7df85cb8810cebf50608a',
    messagingSenderId: '526856370239',
    projectId: 'rental-inventory-booking',
    authDomain: 'rental-inventory-booking.firebaseapp.com',
    storageBucket: 'rental-inventory-booking.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIzaTq3Ncs3viqIoPEBU3PpkbhUYazPf8',
    appId: '1:526856370239:android:1d18bdfc2aa5b38d50608a',
    messagingSenderId: '526856370239',
    projectId: 'rental-inventory-booking',
    storageBucket: 'rental-inventory-booking.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj29N9-VwGgJQ4PM_hoSGvVr41J0KiG2Q',
    appId: '1:526856370239:web:e0e6c6e2b7a4300a50608a',
    messagingSenderId: '526856370239',
    projectId: 'rental-inventory-booking',
    authDomain: 'rental-inventory-booking.firebaseapp.com',
    storageBucket: 'rental-inventory-booking.firebasestorage.app',
  );
}