import 'package:dartz/dartz.dart';
import 'package:rental_inventory_booking_app/core/error/failures.dart';
import 'package:rental_inventory_booking_app/features/booking/domain/entities/booking.dart';
import 'package:rental_inventory_booking_app/features/booking/domain/repositories/booking_repository.dart';

class CreateBooking {
  final BookingRepository repository;

  CreateBooking(this.repository);

  Future<Either<Failure, Booking>> call(Booking booking) async {
    return await repository.createBooking(booking);
  }

  // Helper method to create a booking from individual parameters
  Future<Either<Failure, Booking>> createFromParams({
    required String clientId,
    required String clientName,
    required String clientPhone,
    String? clientEmail,
    required String deliveryAddress,
    required List<BookingItem> items,
    required DateTime startDate,
    required DateTime endDate,
    DateTime? eventTime,
    required BookingType eventType,
    String? eventNotes,
    String? deliveryInstructions,
    required String ownerId,
  }) async {
    // Calculate total amount
    final totalAmount = items.fold<double>(
      0.0, 
      (sum, item) => sum + (item.dailyRate * item.quantity * 
          (endDate.difference(startDate).inDays + 1))
    );

    final booking = Booking(
      id: '', // Will be generated by the repository
      clientId: clientId,
      clientName: clientName,
      clientPhone: clientPhone,
      clientEmail: clientEmail,
      deliveryAddress: deliveryAddress,
      items: items,
      startDate: startDate,
      endDate: endDate,
      eventTime: eventTime,
      eventType: eventType,
      eventNotes: eventNotes,
      deliveryInstructions: deliveryInstructions,
      status: BookingStatus.pending,
      paymentStatus: PaymentStatus.pending,
      totalAmount: totalAmount,
      createdAt: DateTime.now(),
      ownerId: ownerId,
    );

    return await repository.createBooking(booking);
  }
}

